#!/bin/sh -e
cd ${0%/*} || exit 1    # run from this directory

wmakeCheckPwd "$WM_PROJECT_USER_DIR/applications" || {
    echo "Error: Current directory is not \$WM_PROJECT_DIR/applications"
    echo "    The environment variables are inconsistent with the installation."
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

[ -n "$FOAM_EXT_LIBBIN" ] || {
    echo "Error: FOAM_EXT_LIBBIN not set"
    echo "    Check the OpenFOAM entries in your dot-files and source them."
    exit 1
}

set -x

wmake utilities/mesh/MongeAmpereSphere
wmake utilities/mesh/addMountain
wmake utilities/mesh/diamondMesh
wmake utilities/mesh/dualRemoveTriangles
wmake utilities/mesh/edgeCollapser
wmake utilities/mesh/meshStructure
wmake utilities/mesh/orthogonality
wmake utilities/mesh/polyDualPatch
wmake utilities/mesh/setResolution
wmake utilities/mesh/tanPoints
wmake utilities/mesh/VoronoiSphereMesh
wmake utilities/mesh/writeCellFaceCentres

wmake utilities/postProcessing/calcPV
wmake utilities/postProcessing/vorticityDual
wmake utilities/postProcessing/writeCellData
wmake utilities/postProcessing/writeSphuvw

wmake utilities/preProcessing/addPerturbation
wmake utilities/preProcessing/isothermalBalance/isothermalBalance_H
wmake utilities/preProcessing/isothermalBalance/isothermalBalance_dpdx
wmake utilities/preProcessing/makeSK94perturb
wmake utilities/preProcessing/set3dJet
wmake utilities/preProcessing/setAtmosProfile
wmake utilities/preProcessing/setExnerThetaFromT/setExnerThetaFromT_H
wmake utilities/preProcessing/setJet
wmake utilities/preProcessing/setPlaneJet
wmake utilities/preProcessing/setT
wmake utilities/preProcessing/setUlinearp
wmake utilities/preProcessing/setWilliMountain
wmake utilities/preProcessing/setWilliSteady
wmake utilities/preProcessing/stratifiedBalance/stratifiedBalance_H

wmake utilities/test/departurePointStencil
wmake utilities/test/mappedPatch
wmake utilities/test/normalModes
wmake utilities/test/testEigenSVD
wmake utilities/test/testPerp
wmake utilities/test/testSnGran
wmake utilities/test/testTRiSK

wmake solvers/shallowWaterFoam/vecInv

# ----------------------------------------------------------------- end-of-file
